# Generated by Django 5.2.16 on 2026-07-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.CharField(max_length=20)),
                ('defecto', models.CharField(blank=True, max_length=100)),
                ('confianza', models.FloatField()),
                ('archivo', models.CharField(max_length=255)),
                ('origen', models.CharField(max_length=50)),
            ],
        ),
    ]
